### ISSUE TITLE
In the readme, "Rake Information" looks like it's supposed to have links but doesn't.

### ISSUE THREAD

**Issue by Shelvetco** [ruby/rake#110]
[Direct link](https://github.com/ruby/rake#rake-information)

It looks like this: 

### Rake Information

* Rake command-line
* Writing Rakefiles
* The original Rake announcement
* Rake glossary

The text makes me think they're meant to be links, but I can't click on them from github.

**Comment by hsbt** [comment]
It's link for rdoc. not markdown.
