### ISSUE TITLE
Please add a `last_comment` removal/deprecation warning for now

### ISSUE THREAD

**Issue by connorshea** [ruby/rake#116]
`NoMethodError: undefined method 'last_comment' for #<Rake::Application:0x00000002b87b38>` tells me nothing. Can you please add a `Use last_description method` warning for now? It can be removed in v12, but this was kind of a surprise and I don't think most people were expecting it.

**Comment by kpheasey** [comment]
This is causing me headaches with a Rails 5 engine.

**Comment by bbatsov** [comment]
Supposedly this was deprecated a while back, although I haven't seen a deprecation message myself. Most projects quickly released updated rake tasks, with yard being one notable exception so far. It seems to me we're past the point of adding this back - just search for this on GitHub. :-)

**Comment by dsawa** [comment]
+1, wasn't expecting that.

**Comment by markandrewj** [comment]
+1

**Comment by hsbt** [comment]
I released Rake 11.1.0 with reverting to `last_comment` and deprecate it. I wiil remove it at Rake 12. Please report or submit patch to dependency of your application with deprecated usage.

**Comment by bronson** [comment]
@hsbt just curious, why did you remove `last_comment`?  I can't find a reason in the [commit](https://github.com/ruby/rake/commit/e76242ce7ef94568399a50b69bda4b723dab7c75) or the [issues](https://github.com/ruby/rake/issues?utf8=%E2%9C%93&q=last_comment).  Why the churn?

**Comment by connorshea** [comment]
@hsbt thank you! :)

**Comment by bramski** [comment]
Would have been great if this deprecation included some context.  I'm seeing this everytime I run rake.
```
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
```
I've grepped my whole codebase which would leave me with grepping my gems to figure out who hasn't upgraded yet.  Sweet.

**Comment by hsbt** [comment]
You need to upgrade rspec or rspec-rails.
