### ISSUE TITLE
Please add a flag to TestTask for the old verbose behavior

### ISSUE THREAD

**Issue by pwnall** [ruby/rake#125]
Before 6495738dbc3468ea400eec983746cb49ef6226cc, setting `verbose` to true displayed the command line used to run the tests. After that commit, the `verbose` option also enables warnings.

Can you please add an attribute that only does the former?

**Comment by hsbt** [comment]
@pwnall I investigate verbose behavior Rake 11. I found a bug with verbose mode on Rake 11. 

Expected: `ruby -Ilib test/foo_test.rb --verbose`
Actual: `ruby --verbose -Ilib test/foo_test.rb`

I misunderstood `verbose` option with https://github.com/ruby/rake/pull/67 at minitest. #67 says `The verbose option needs to be forwarded to the Ruby call.`, but `verbose` option on Rake::TestTask means minitest's it.

I'm going to revert #67 and release Rake 11.1.2.

**Comment by hsbt** [comment]
Ah. I'm also misunderstanding above comments. I'm going to remove "-W" option and only show details of command line with test runner.

**Comment by hsbt** [comment]
@pwnall I released Rake 11.1.2. Please try it.

**Comment by MarkDBlackwell** [comment]
See [this comment](https://github.com/ruby/rake/pull/67#issuecomment-235167629).
