### ISSUE TITLE
Please remove [DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.

### ISSUE THREAD

**Issue by joelpresence** [ruby/rake#133]
Hi,

Thanks for all of your hard work on rake!  :-)

I upgraded from rake 10.5.0 to 11.1.2 to avoid
```
shell> rake routes
rake aborted!
Gem::LoadError: You have already activated rake 11.1.2, but your Gemfile requires rake 10.5.0. Prepending `bundle exec` to your command may solve this.
/Users/joel/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/runtime.rb:34:in `block in setup'
/Users/joel/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/runtime.rb:19:in `setup'
/Users/joel/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
/Users/joel/.rvm/gems/ruby-2.2.2/gems/bundler-1.11.2/lib/bundler/setup.rb:8:in `<top (required)>'
/Users/joel/src/user_data/config/boot.rb:3:in `<top (required)>'
/Users/joel/src/user_data/config/application.rb:1:in `<top (required)>'
/Users/joel/src/user_data/Rakefile:4:in `<top (required)>'
LoadError: cannot load such file -- bundler/setup
/Users/joel/src/user_data/config/boot.rb:3:in `<top (required)>'
/Users/joel/src/user_data/config/application.rb:1:in `<top (required)>'
/Users/joel/src/user_data/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```
The error above would only disappear if I used `bundle exec rake` and that's way too much to type and remember when doing local development and testing.

So I did `bundle update rake` which updated me from 10.5.0 to 11.1.2 and now I get the following 6 errors every single time I run rake:
```
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
```
This is polluting my logs and I would really prefer if we could remove this or silence it somehow.  I am not using last_comment anywhere in any of my code.  We use rake a lot for jobs, reports, tests, etc. and this new deprecation message is really cluttering our logs and making it difficult to see more important log messages.

I see issue https://github.com/ruby/rake/issues/116.  However, this deprecation error is polluting my logs both locally in development and test as well as in production.

I saw mention in issue 116 that this might have something to do with ruby versions.  We are using `ruby 2.2.2p95` for compatibility with Heroku.  This is a large production application and we can't just upgrade our version of ruby to eliminate this deprecation warning.

Is there some way that we can either turn off this deprecation warning or offer a way to silence it?  I would be happy to help with a fix if you can suggest where to look and would be willing to code review my push.  :-)

Thanks!

**Comment by joelpresence** [comment]
OK, I did `gem uninstall rake` and uninstalled 11.1.2, so my rvm is back to using rake 10.5.0.  Not sure how 11.1.2.  So I have gotten this deprecation warning to disappear for now ...

But I would still like to be able to update to rake 11.1.2 without upgrading my ruby and without seeing this deprecation warning.  Any suggestions?

Thanks!

**Comment by hsbt** [comment]
You need to upgrade rspec probably.

**Comment by joelpresence** [comment]
@hsbt thanks.  I see https://github.com/rspec/rspec-core/issues/2210 so I wonder if upgrading from rspec-rails 3.3.3 to 3.4.2 would help?

**Comment by hsbt** [comment]
rspec-rails is not related this. you need to upgrade `rspec-core-3.4.4` or later.

**Comment by joelpresence** [comment]
@hsbt I don't reference rspec-core in my Gemfile.  It is brought in as a dependency of rspec-rails.

**Comment by hsbt** [comment]
I see. do upgrade rspec-core.

**Comment by born-in-brooklyn** [comment]
This error is back again
