### ISSUE TITLE
NoMethodError: undefined method `task' for main:Object

### ISSUE THREAD

**Issue by bodaonline** [ruby/rake#136]
Hi All,

have a rake task which worked before. Now after a bundle update with Rake 11.1.2 it only works from the console without the first line "task :fetch_ttt => :environment do". This line gives the "NoMethodError: undefined method `task' for main:Object"

Reverting to 10.5.0 doesn't help. Described the issue in detail [here](http://stackoverflow.com/questions/37281963/rake-task-nomethoderror-undefined-method-task-for-mainobject)

ps: beginner here

**Comment by bodaonline** [comment]
Outcommented these and now OK
      #require 'nokogiri'
      #require 'open-uri'

**Comment by hsbt** [comment]
I can't reproduce it with following code

```
task :foo do
  require 'open-uri'
  require 'nokogiri'
end
```

Please provide minimum reproduction code without Rails.
