### ISSUE TITLE
Rake Jobs

### ISSUE THREAD

**Issue by NovaMoon** [ruby/rake#152]
So im not sure if this is the right place here to ask but i give it a shot. 

im running a imageboard written in ruby and it has a feature utilizing batch uploads with rake jobs so i tried as recommended by the dev.

`bundle exec rake create_jobs` with `bundle exec rake job:start`

and the worker starts correctly with no errors but its not doing the upload. 

i checked different logs but nothing shows an error besides the "development.log" looping the action

**Comment by hsbt** [comment]
It's not rake issue. You need to investigate what gem provides `job:start` task and submit it gem tracker.
