### ISSUE TITLE
`rake -AT` works, but `rake -TA` does not

### ISSUE THREAD

**Issue by tombaker** [ruby/rake#155]
This works (`-AT`): 
```
$ rake -AT
(in /Users/tbaker/codebox)
rake rmtilde         #
rake turn_off_alarm  #
rake walk_dog        # Walk dog
```

But this does not (`-TA`):
```
$ rake -TA
(in /Users/tbaker/codebox)
```

Even though this works (`-T -A`):
```
$ rake -T -A
(in /Users/tbaker/codebox)
rake rmtilde         #
rake turn_off_alarm  #
rake walk_dog        # Walk dog
```
This is potentially confusing.

**Comment by hsbt** [comment]
@tombaker It's affected by `-T` option specification. `-T` allows to add filtering words.

I added help message about `-AT` combination at https://github.com/ruby/rake/commit/01657b91e0bbde0a3b1530ac165eaa8a1cb07d5d

**Comment by tombaker** [comment]
On Sat, Aug 27, 2016 at 04:20:42PM -0700, SHIBATA Hiroshi wrote:
> @tombaker It's affected by `-T` option specification. `-T` allows to add filtering words.
> 
> I added help message about `-AT` combination at https://github.com/ruby/rake/commit/01657b91e0bbde0a3b1530ac165eaa8a1cb07d5d

Thank you!
Tom Baker

-- 
Tom Baker <tom@tombaker.org>
