### ISSUE TITLE
Gem::InstallError: rack requires Ruby version >= 2.2.2

### ISSUE THREAD

**Issue by khalidh12** [ruby/rake#170]
An error occurred while installing rack (2.0.1), and Bundler cannot continue.
Make sure that `gem install rack -v '2.0.1'` succeeds before bundling.

i am trying to install "gem install rack -v '2.0.1'"
ERROR:  Error installing rack:
	rack requires Ruby version >= 2.2.2.

i am using
ruby 2.1.1 version
bundler 1.6.0(and tried with bundler 1.13.3)

ruby 2.1.1 version mandatory because of some other gems dependent on this version

**Comment by hsbt** [comment]
This repository is **rake**

**Comment by branyster** [comment]
You the man hsbt !

I too had this error !

Error installing passenger:
rack requires Ruby version >= 2.2.2.


gem install rake      (command worked)

Successfully installed for rake-11.3.0
