### ISSUE TITLE
Is it possible to do on-demand loading of rake tasks?

### ISSUE THREAD

**Issue by ioquatix** [ruby/rake#176]
And if not, would this be a good idea for a pull request?

**Comment by ioquatix** [comment]
Okay just to flesh this out - on-demand loading should minimise the time it takes to load and run tasks when there are hundreds of .rake files

It would only apply to namespaces, and there could either be a dynamic loading scheme or a static loading scheme. Both probably useful as we have a ton of legacy stuff

The idea would be something like this:

For static things:

```ruby
namespace :db => File.expand_path("db.rake", __dir__)
```

For dynamic things

```ruby
namespace File.join(__dir__, "tasks")
```

Open to ideas, suggestions, etc.

**Comment by ioquatix** [comment]
If I can just get a sign that this is something that would be accepted/merged (within reason), I'll work on a PR.

**Comment by shreyasbharath** [comment]
This would be extremely useful! I have previously resorted to manually writing logic in Rakefiles to only load the tasks that are necessary based on the top-level tasks passed in by the user.

**Comment by lionelperrin** [comment]
I've created a PR for this purpose: #339.

**Comment by ioquatix** [comment]
I like your PR. I really like rake, but I decided to try fixing this in a new gem: https://github.com/ioquatix/bake
