### ISSUE TITLE
Importing contrib libs crash on rake v.12.0

### ISSUE THREAD

**Issue by c0m3tx** [ruby/rake#179]
On Rake v.12.0.0 with the following rakefile

    require 'rake/contrib/ftptools'

i get

    rake aborted!
    LoadError: cannot load such file -- rake/contrib/ftptools
    /home/user/Rakefile:3:in `<top (required)>'
    /home/user/.gem/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'

Tried with Rake v. 11.3.0 and it works.

**Comment by hsbt** [comment]
Use https://github.com/ruby/rake-contrib

**Comment by c0m3tx** [comment]
Already installed that gem, but with rake v. 12 it does not seem to work. I'm, however, able to require rake/contrib/ftptools without any problem from irb.

**Comment by drbrain** [comment]
Likely your `irb` and `gem` use one ruby version while `rake` uses a different ruby version, so they are looking at different gems.

A rake task that prints out `RUBY_DESCRIPTION` and `Gem.path` and `$LOAD_PATH` compared to printing the same in `irb` should help you diagnose this.

**Comment by c0m3tx** [comment]
Sorry for getting back to you so late. Last time I resolved rolling back to rake version 11, but yesterday my ruby updated so I had to reinstall all gems (which brought me back to version 12).

Rake RUBY_DESCRIPTION and Gem.path

   ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
   /home/c0m3tx/.gem/ruby/2.4.0
   /usr/lib/ruby/gems/2.4.0

IRB/Ruby RUBY_DESCRIPTION and Gem.path
   
   irb(main):001:0> RUBY_DESCRIPTION
   => "ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]"
   irb(main):002:0> Gem.path
   => ["/home/c0m3tx/.gem/ruby/2.4.0", "/usr/lib/ruby/gems/2.4.0"]

**Comment by c0m3tx** [comment]
One more thing i noticed:

    ~ irb
    irb(main):001:0> require 'rake/contrib/ftptools'
    => true
    irb(main):002:0> require 'rake'
    => true

but

    ~ irb
    irb(main):001:0> require 'rake'
    => true
    irb(main):002:0> require 'rake/contrib/ftptools'
    LoadError: cannot load such file -- rake/contrib/ftptools
    	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
    	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
    	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    	from (irb):2
	from /usr/bin/irb:11:in `<main>'

**Comment by hsbt** [comment]
@c0m3tx Thank you. I try to reproduce it.

**Comment by c0m3tx** [comment]
Sent a pull request to rake-contrib with a bugfix.

https://github.com/ruby/rake-contrib/pull/1

Let me know if any issue arises.
