### ISSUE TITLE
Is the removal of last_comment worth it?

### ISSUE THREAD

**Issue by eregon** [ruby/rake#188]
The removal of `last_comment` triggered several issues.
One important one is that older gems which just depend on `gem 'rake'` are no longer testable (for instance because they depend on an older rspec which uses `last_comment`).
One workaround would be to change the version requirement in their gemspec/Gemfile, which is very unfortunate.

What is the motivation behind removing last_comment?
Is it worth for maintainability to break many older gems which have no specific version requirement on `rake`?

cc @bjfish

**Comment by hsbt** [comment]
> What is the motivation behind removing last_comment?

Code maintainability. It was code that was left only for backwards compatibility and was meaningless.

> The removal of last_comment triggered several issues.

see https://github.com/ruby/rake/issues/116 .

I warned It after Rake 11.1.0 at last year. So, Rake 12 is major version-up contained breaking changes. You can use old/unmaintained gem with Rake 10 or 11.

Finally, I have no plan to revert `last_comment` removal change. I'm so tired about this discussion.

**Comment by eregon** [comment]
@hsbt I see, thank you for the reply.
I looked at related issues but did not see the motivation.
Sorry for the noise.
