### ISSUE TITLE
Setting TEST environment variables makes rake crash

### ISSUE THREAD

**Issue by giovannibenussi** [ruby/rake#194]
I spend hours trying to debug this error that doesn't let me run `rake test` (and also `rake test`). Run anyone of those commands throws this error:

```
/Users/my_username/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- /Users/my_username/tmp/ruby/pretty_monkey/this_is_a_test (LoadError)
	from /Users/my_username/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/my_username/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /Users/my_username/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:4:in `select'
	from /Users/my_username/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1)
/Users/my_username/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/my_username/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:17:in `eval'
/Users/my_username/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:17:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

After a time searching for the error I find that the error throws because I set the **TEST** environment variable (e.g: `export TEST="this_is_a_test"`).

**Comment by drbrain** [comment]
This is expected behavior [per the documentation](https://github.com/ruby/rake/blob/master/lib/rake/testtask.rb#L30).

If you don't have a `this_is_a_test.rb` file then you will get that error.  You will need to use the name of a test file you do have instead.

**Comment by giovannibenussi** [comment]
You're right. But it shouldn't at least leave a error message if the file doesn't exists?
I think that is a very difficult bug to track.

Cheers.

**Comment by mblumtritt** [comment]
"cannot load such file" sounds like an error message for me.

**Comment by drbrain** [comment]
@giovannibenussi is #195 better?
