### ISSUE TITLE
Rake Arguments

### ISSUE THREAD

**Issue by Ch4s3** [ruby/rake#197]
I'm looking for a good resource on passing arguments to rake, but can't find anything recent, accurate, or that works.

I'm trying to pass a number of weeks for running a report and 0-Many email addresses to send the report to.
like `rake report:foo 1 Chase@myemail.test` or `rake report:foo[1,Chase@myemail.test]` but I can't get either to reliably work. I can parse `rake report:foo 1 Chase@myemail.test` with `ARGV` but I get the following error:
```bash
rake aborted!
Don't know how to build task '1' (see --tasks)
```
For the latter `rake report:foo[1,Chase@myemail.test]` I can't figure out how to access a variable number of args e.g. `rake report:foo[1,Chase@myemail.test,coworder@myemail.test]`, or just `rake report:foo[1]`

Where can I read up on how to do this correctly?

**Comment by murdocdv** [comment]
Have you tried wrapping it in quotes?
`rake "report:foo[1,Chase@myemail.test]"`

**Comment by drbrain** [comment]
Please read [Tasks with Arguments](https://github.com/ruby/rake/blob/master/doc/rakefile.rdoc#tasks-with-arguments) section of the documentation.

Example:

```ruby
# t.rake
task 'report:foo', [:id, :email] do |t, args|
  puts "Generating report id #{args.id} for #{args.email}"
end
```

Running it:

```
$ rake -f t.rake report:foo[1,user@example.com]
Generating report id 1 for user@example.com
```

Note that passing parameters to other tasks that require them is clumsy.  The best way I've found to do it is this:

```ruby
namespace :report do
  task :args, [:id, :email] do |t, args|
    $id    = args.id
    $email = args.email
  end

  task :check_args do
    abort <<-MESSAGE unless $id and $email
You must provide args via the report:args task, for example:

  $ rake report:args[ID,EMAIL] report:foo

    MESSAGE
  end

  task foo: :check_args do
    puts "Generating report id #{$id} for #{$email}"
  end
end
```

Running it:

```
$ rake -f t.rake report:foo
You must provide args via the report:args task, for example:

  $ rake report:args[ID,EMAIL] report:foo

$ rake -f t.rake report:args[1,user@example] report:foo
Generating report id 1 for user@example
```
