### ISSUE TITLE
A way to show the tasks

### ISSUE THREAD

**Issue by fulldecent** [ruby/rake#204]
`rake --tasks` will show you the tasks.

From inside a rake task you can use:

```ruby
# http://stackoverflow.com/a/11320444/300224
Rake::TaskManager.record_task_metadata = true
desc "Show all the tasks"
task :default do
  Rake::application.options.show_tasks = :tasks  # this solves sidewaysmilk problem
  Rake::application.options.show_task_pattern = //
  Rake::application.display_tasks_and_comments
end
```

There should be a more intuitive way to do this. I propose:

```ruby
task :default => :show_tasks
```

**Comment by drbrain** [comment]
I think this is best done as an extension gem for rake.

I don't think rake should provide tasks as alternatives for command line options.

**Comment by mblumtritt** [comment]
My default task looks often like this:

```ruby
task :default do
  system 'rake -T'
end
```

This avoids all the magic and is short enough to remeber it in the next project :)

**Comment by Willamin** [comment]
The idea of "convention over configuration with sane defaults" would dictate that a default task of `system 'rake -T'` would make sense, right?
