### ISSUE TITLE
Active Model cache is out of date after using db:migrate as a prerequisite

### ISSUE THREAD

**Issue by sbwoodside** [ruby/rake#207]
Following the instructions in https://stackoverflow.com/a/24496452/102675 I wound up with the following:

```ruby
namespace :db do
  desc 'Drop, create, migrate, seed and populate sample data'
  task seed_sample_data: [:drop, :create, :migrate, :seed, :populate_sample_data] do
    puts 'Sample Data Populated. Ready to go!'
  end

  desc 'Populate the database with sample data'
  task populate_sample_data: :environment do
    puts Inspector.column_names.include?('how_to_fix')
    # create my sample data
  end
end
```

As you would expect, I got `true` if I run `bundle exec rake db:populate_sample_data`

BUT when I ran `bundle exec rake db:seed_sample_data` I got all the migration output and then `false`. In other words I can't see the `Inspector` attribute `how_to_fix` even though it definitely exists as proved by the other rake run. Where did my attribute go?

It appears that the cache of the ActiveRecord Model/Attributes is out of date. I can access some of the attributes, but not all of them (not the ones in later migrations). If I add this I get the correct output:

```ruby
Inspector.reset_column_information
```

_Desired behaviour:_

Update the cache automatically after running migrations.

**Comment by drbrain** [comment]
You need to file this against a different project, maybe something in Rails?

Rake itself does not provide any tasks for seeding databases.
