### ISSUE TITLE
Commas in string arguments?

### ISSUE THREAD

**Issue by bootstraponline** [ruby/rake#21]
Would rake accept a patch that enabled commas in string arguments to rake?

http://stackoverflow.com/questions/7258148/how-can-i-use-a-comma-in-a-string-argument-to-a-rake-task

**Comment by heemin32** [comment]
I think this issue was already handled in #70, #150.

**Comment by bootstraponline** [comment]
No, I think it's still a bug. I ran into the same issue as described on stackoverflow with string arguments containing a comma.

**Comment by drbrain** [comment]
Using your example, is escaping insufficient?

```
$ rake test_commas["a\,b"]
a,b
```

**Comment by bootstraponline** [comment]
In Thor I can do "a,b" without escaping. I guess this isn't easy to do in rake?

**Comment by drbrain** [comment]
Escaping is required as rake uses `,` to separate arguments and allows variable arguments.

**Comment by bootstraponline** [comment]
Thanks for explaining.
