### ISSUE TITLE
Wrong release Date in gemspec/on rubygems.org

### ISSUE THREAD

**Issue by themilkman** [ruby/rake#222]
Hi there,

since it was (at least for me ;-) ) quite confusing, I just wanted to point out that the date of the latest release is wrong in the gemspec (and thus rubygems.org):

` s.date = "2016-12-06"`

Cheers!

**Comment by hsbt** [comment]
Thanks. I update release date(https://github.com/ruby/rake/commit/3d6df97a6fbc44572e08b39e5bc4aed87a3a6278)
