### ISSUE TITLE
Using rake to run a file

### ISSUE THREAD

**Issue by crocodileDundee** [ruby/rake#229]
Hi :wave: 
I didn't find anything like this in the issue list, so I am making a new one.

I have the environment variables of my app in a file like this:

```
export VARIABLE=VALUE
... etc
```

When I run the tests, I have to remember to run this file before, or the tests will fail. So I created a task in my Rakefile to automatically run this file before running the tests. But it is not working.

I tried this:

```
task :env_test { sh('source ./credentials/.env_test') }
```
But I get the error:

```
source ./credentials/.env_test
rake aborted!
Command failed with status (127): [source ./credentials/.env_test...]
```

I also tried:

```
task :env_test { `source ./credentials/.env_test` }
```

and got:

```
rake aborted!
Errno::ENOENT: No such file or directory - source
```
I also tried:

```
task :env_test { `. ./credentials/.env_test` }
```

for which all tests using environment variables fail, as if the credentials weren't set, which can only happen if `.env_test` was not run.

Finally I tried:

```
task :env_test { `./credentials/.env_test` }
```

and again tests fail.

What am I doing wrong?

**Comment by crocodileDundee** [comment]
Hello, any news on this? :slightly_smiling_face:

**Comment by yuki24** [comment]
Rake is not responsible for managing `ENV` variables. Please use a third-party gem like the [foreman](https://github.com/ddollar/foreman), [dotenv](https://github.com/bkeepers/dotenv), or [figaro](https://github.com/laserlemon/figaro) gem.

**Comment by crocodileDundee** [comment]
@yuki24 Hi, sorry I think I didn't make myself clear

The fact that this file contains environment variables is irrelevant to the question.
The problem is that I am using a shell command to run a bash file and rake seems to have a problem with that. Is it possible that rake runs shell commands in a sandbox or a separate shell instance?

**Comment by yuki24** [comment]
I think it is just s a path/user issue. Try running commands like the followings to figure out what circumstances rake is run under:

```ruby
task :whoami do
 sh 'whoami'
end

task :pwd do
  sh 'pwd'
end

task :echo_path do
  sh 'echo $PATH'
end
```

Then you could try running the same commands in your shell. Also, rake starts up a new process to run the job. This means that even if it could resolve and find the `source` executable correctly the environment variables in your `./credentials/.env_test` wouldn't be loaded in the parent rake process.

**Comment by crocodileDundee** [comment]
Thank you @yuki24 , that worked. 

I get the same as my shell for `whoami` and `pwd`, but for `echo_path` I get these extra paths on top of the paths that were output by my shell:

```
/home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bin:/home/ubuntu/.rbenv/versions/2.4.1/bin:/home/ubuntu/.rbenv/libexec:/home/ubuntu/.rbenv/plugins/ruby-build/bin:
```

If I understand correctly from your comment, running bash files from a rake task will happen in a child rake process and not in the parent (whatever that means! :slightly_smiling_face:)

Is this difference in the `echo` command related to that?
And how could we run bash files in the parent rake process?

**Comment by yuki24** [comment]
Processes are not designed to run executables within the same process. It's not just Ruby but any type of program that is run in any unix-based system.
