### ISSUE TITLE
Current rake & 1.9.3

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/rake#230]
I was looking at another gem's Travis, and there were issues with 1.9.3, and an (upgraded) rake was one of the dependencies.

[Gemspec](https://github.com/ruby/rake/blob/f7b96895832360f6a254b67c1b07d0b205494363/rake.gemspec#L33) shows ruby >= 1.9.3, but it isn't tested with it.  Sure its okay?

**Comment by hsbt** [comment]
It prefers to update `>= 2.0.0` on gemspec.

**Comment by rickhull** [comment]
It would be good to have an example, if not a test case for this.  Still, I created a PR #236 per @hsbt's suggestion.
