### ISSUE TITLE
Minor typo in README

### ISSUE THREAD

**Issue by Alanocallaghan** [ruby/rake#238]
Hi, sorry to be "that guy" but I spotted this omission when browsing the README. 

>(Formerly tasks for building RDoc, Gems and publishing to FTP were included in rake but they're now available in RDoc, RubyGems and respectively.)

**Comment by hsbt** [comment]
Where is typo in README?

**Comment by Alanocallaghan** [comment]
"available in RDoc, RubyGems and respectively" suggest that a third item (for publishing to FTP) will be listed, but it isn't

**Comment by hsbt** [comment]
I welcome to pull-request. Thanks.
