### ISSUE TITLE
Travis CI is not testing PRs

### ISSUE THREAD

**Issue by colby-swandale** [ruby/rake#281]
I've noticed that travis-ci is not testing PRs, i can see in a recent [PR that i made](https://github.com/ruby/rake/pull/280) that we're only using appveyor, which makes me think that we should also be using travis (the config is also there). The last build for a PR seems to be about [2 years ago](https://travis-ci.org/ruby/rake/pull_requests). Is there any specific reason for this or is this mis-configuration?

**Comment by hsbt** [comment]
I enabled its configuration on Travis CI now. Can you check it again?

**Comment by colby-swandale** [comment]
🎉

It's now working https://github.com/ruby/rake/pull/283.

Thank you @hsbt
