### ISSUE TITLE
Alternative to `Rakefile`

### ISSUE THREAD

**Issue by svoop** [ruby/rake#296]
In the light of Bundler 2 dropping `Gemfile` in favour of `gems.rb` (while still accepting `Gemfile` for most likely a long while to come):

How about adding a similar alternative to Rake, say, accept both `rake.rb` and `Rakefile`?

The first will be more appropriate in the context of e.g. a Rails app, whereas the latter looks nicer whenever using Rake as a replacement for Make.

**Comment by colby-swandale** [comment]
Hi! Rake already has support for `rakefile.rb`. You can [check here](https://github.com/ruby/rake/blob/master/lib/rake/application.rb#L41) for the full list of support filenames.
