### ISSUE TITLE
Proposal on releasing Rake 13

### ISSUE THREAD

**Issue by colby-swandale** [ruby/rake#302]
With the release of Ruby 2.6 and the EOL of Ruby 2.3 approaching soon, it seems like a good time to release a new major version of Rake that drops support for versions of Ruby that are no longer supported.

My proposal is to drop official support for the following ruby versions:
- 2.0.0
- 2.1.10
- 2.2.10

This would also allow any breaking changes to be introduced. I don't know what, if any there are that can be released.

Any thoughts are welcome.

\cc @hsbt

**Comment by hsbt** [comment]
There are no breaking changes yet on Rake 12. When We want to use keyword args or other useful methods of the current stable versions, I will release Rake 13.

It is not that time now.

**Comment by colby-swandale** [comment]
Thank you for the explanation
