### ISSUE TITLE
warning: deprecated Object#=~ is called on Proc; it always returns nil

### ISSUE THREAD

**Issue by localhostdotdev** [ruby/rake#308]
I'm using ruby-head, `ruby 2.7.0dev (2019-03-18 trunk 67296) [x86_64-darwin17]` and getting lot of those warnings:

```
.rvm/gems/ruby-head/gems/rake-12.3.1/lib/rake/application.rb:395: warning: deprecated Object#=~ is called on Proc; it always returns nil
```

Code:

```
    def sort_options(options) # :nodoc:
      options.sort_by { |opt|
        opt.select { |o| o =~ /^-/ }.map(&:downcase).sort.reverse
      }
    end
```

I guess it should be safe to delete it as it always returns nil per the warning.

**Comment by hsbt** [comment]
It's already fixed. Do upgrade 12.3.2.

https://github.com/ruby/rake/commit/f0a897e3fb557f64f5da59785b1a4464826f77b2

**Comment by localhostdotdev** [comment]
Oh, thanks, I looked at the issues/PRs but forgot to look at the commits.
