### ISSUE TITLE
Calling a task with unexpected arguments should fail

### ISSUE THREAD

**Issue by grosser** [ruby/rake#314]
```
task(:foo) { }
rake foo[wtf,this,should,not,work]
```

... on top of that the `args` argument that is returned to the block does not know about the extra arguments, so I can't even add my own argumenterror if I wanted to

I can make a PR to fix this, just want consensus that that is desired behavior

**Comment by fatkodima** [comment]
@grosser 
Are you talking about something like this?
https://github.com/ruby/rake/blob/c2eeae2fe2b67170472a1441ebf84d3a238c3361/lib/rake/task_arguments.rb#L31-L34

**Comment by grosser** [comment]
that looks like what I want to get the args

would still prefer for `foo[wut]` to fail but that might be hard to pull off without breaking backwards compatibility :/
