### ISSUE TITLE
Show all task when `rake -T` is executed 

### ISSUE THREAD

**Issue by taki** [ruby/rake#344]
## Description

Currently, `rake -T` command show only task with description. I want to show all defined task because I do not notice that **task2** is defined.
How do you think? If you think it is not sure, Please feel free to close.

Thank you.

## Example

Below is Rakefile and `rake -T` is executed.

```ruby
desc 'task1'
task :task1

task :task2
```

### Current

```console
rake task1  # task1
```

### Feature

```console
rake task1  # task1
rake task2
```

**Comment by hsbt** [comment]
I always used `rake -AT`. Is it enough for your expectations?

**Comment by taki** [comment]
> I always used `rake -AT`. Is it enough for your expectations?

`rake -AT` is enough. Thank you.
