### ISSUE TITLE
Documentation-related: 404 in the Jim Weirich presentation

### ISSUE THREAD

**Issue by pjump** [ruby/rake#35]
It used to work some time ago, now it doesn't.
A direct link works for the main page: http://onestepback.org/articles/buildingwithrake/ , but sublinks are broken. Anyone knows of a working copy?

**Comment by bsvin33t** [comment]
Even if we do get this, what are the next steps? 
Where do we host them?

**Comment by pjump** [comment]
It's just static content. Github is gives you free hosting for static webpages too, I believe.

**Comment by drbrain** [comment]
Can it be extracted from archive.org?

**Comment by hsbt** [comment]
We already used http://web.archive.org/web/20140221123354/http://onestepback.org/articles/buildingwithrake/
