### ISSUE TITLE
Broken links in the documentation

### ISSUE THREAD

**Issue by dmitriyshashkin** [ruby/rake#391]
All the links in the "Rake Information" section lead to 404: https://ruby.github.io/rake/#label-Rake+Information

**Comment by siaw23** [comment]
@hsbt can we close this since it's been fixed; to reduce clutter?

**Comment by msugakov** [comment]
[Writing Rakefiles](https://ruby.github.io/rake/doc/rakefile.rdoc) link takes to 404.
