### ISSUE TITLE
How to add global task dependency?

### ISSUE THREAD

**Issue by zotherstupidguy** [ruby/rake#44]
Is there a way to ensure that all tasks run a specific task without writing it as a prerequisite for each individual rake task?

**Comment by drbrain** [comment]
No.

Can you do this with `make`?

**Comment by zotherstupidguy** [comment]
please clarify @drbrain, for me it doesn't make since to use make with ruby code!

**Comment by pjump** [comment]
I don't think this belongs on the issue tracker, but you can accomplish what you're asking for just by including the code in the Rakefile. The Rakefile is ruby code that runs once and that runs before any task is invoked, ergo Rakefile is the global prerequisite.

**Comment by pjump** [comment]
Or a *.rake file in rakelib/. All those behave like a global prerequisite to any and all tasks.

**Comment by drbrain** [comment]
Rake's historical feature set is based and restricted by `make`'s feature set.

If you can define a `make` rule that always runs then it makes sense for `rake` to have such a feature.  If not, then the barrier to acceptance becomes higher.

As @pjump says, you can use regular ruby code for something that always run when you run `rake`.
