### ISSUE TITLE
directory should accept a FileList

### ISSUE THREAD

**Issue by jasonkarns** [ruby/rake#494]
I was shocked to learn that `directory files.pathmap("%d")` doesn't work.

```
rake aborted!
TypeError: no implicit conversion of Rake::FileList into String
```

Does this seem like a reasonable feature request?

**Comment by mblumtritt** [comment]
The directory method uses a string as parameter. But you can

```ruby
files.pathmap("%d").each{ |name| directory name}
```

**Comment by jasonkarns** [comment]
> The directory method uses a string as parameter

Precisely. That's what I'm suggesting is the deficiency. FileLists are the core primitive of rake. It's how file tasks are generated. `directory` itself is a wrapper for file tasks. It's incongruent for some file tasks to accept FileLists but not others.
