### ISSUE TITLE
rake error on redmine

### ISSUE THREAD

**Issue by ritech** [ruby/rake#531]
new system ubuntu 22.04
root@ubuntu:/opt/redmine# rake tmp:cache:clear tmp:sessions:clear RAILS_ENV=production
rake aborted!
Don't know how to build task 'tmp:sessions:clear' (See the list of available tasks with `rake --tasks`)
Did you mean?  tmp:sockets:clear
/var/lib/gems/3.0.0/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
root@ubuntu:/opt/redmine#

**Comment by hsbt** [comment]
It's not rake issue. Please ask `redmine` or your project.
