### ISSUE TITLE
binary-or assignment on purpose?

### ISSUE THREAD

**Issue by awwaiid** [ruby/rake#57]
Is the "|=" binary-or assignment operator used here on purpose?

https://github.com/ruby/rake/blob/master/lib/rake/task.rb#L101
```@prerequisites |= deps if deps```

I haven't looked into it, just thought I'd ask.

**Comment by drbrain** [comment]
Yes, it adds the extra dependencies to the task's current dependency list.  See [Array#|](http://docs.ruby-lang.org/en/2.2.0/Array.html#method-i-7C)

**Comment by awwaiid** [comment]
Thanks for the pointer!
