### ISSUE TITLE
no rake.gemspec in repository

### ISSUE THREAD

**Issue by tmornini** [ruby/rake#60]
Hello. I'd love to see a rake.gemspec added to the repository so that I can use:

```gem 'rake', github: 'tmornini/rake', branch: 'allow_custom_test_loader'```

in Bundler Gemfile. This would make it much easier to submit PRs such as #49.

As it stands, Bundler aborts as it does not believe that the repository is a gem.

**Comment by mblumtritt** [comment]
Yep, that would be nice to use Bundler and start collaboration a second later…

**Comment by hsbt** [comment]
I will prepare it with rake 11

**Comment by tmornini** [comment]
@hsbt Thank  you very much! :+1:
