### ISSUE TITLE
Syntax error: Unexpected tSTRING_BEG

### ISSUE THREAD

**Issue by denpatin** [ruby/rake#68]
Hi guys,

I am not sure whether I am writing to the write place but one weird error has occurred. Below is the screenshot. I presume there might be something wrong with my `rake`? Currently I have the latest ruby and rails versions. And I even cannot check the `rake -v` because this error gets thrown any time I am trying to execute whatever `rake blahblah` command.

<img width="616" alt="screen shot 2015-09-12 at 8 43 53 pm" src="https://cloud.githubusercontent.com/assets/1271040/9832926/1747e226-598f-11e5-9e82-294eb738d74e.png">

Thank you in advance for help!

**Comment by drbrain** [comment]
This isn't a rake issue as that code doesn't come from rake.

To help you find the problem, though, please paste `cat rake` So I can help figure out what is going on.

**Comment by denpatin** [comment]
@drbrain Indeed, that was not a problem with rake. A new ruby installation performed by RVM has not merely put `rake` to the installed gem list. Putting it myself by doing `gem install rake` worked for me. Anyway thanks!
