### ISSUE TITLE
Hoe not found (documentation)

### ISSUE THREAD

**Issue by fulldecent** [ruby/rake#75]
I cloned the repository and ran `rake` from the main directory. This produced the following error:

> Williams-iMac:rake williamentriken$ rake
> rake aborted!
> LoadError: cannot load such file -- hoe
> /Users/williamentriken/Developer/rake/Rakefile:18:in `<top (required)>'
> (See full trace by running task with --trace)
> Williams-iMac:rake williamentriken$ 

There was no mention of this in CONTRIBUTING. Also, "hoe" appears to be a generic word, so searching for the error is difficult on Google.

Using Mac OSX 10.11.1 (15B30a), and rake version 10.4.2.

**Comment by hsbt** [comment]
Thanks your report.

@pvdb fixed at https://github.com/ruby/rake/pull/78
