### ISSUE TITLE
Rake tmp clear

### ISSUE THREAD

**Issue by amnesia7** [ruby/rake#77]
Capybara creates html webpages in the `tmp` directory whenever `save_and_open_page` is used.

Should `rake tmp:clear` not clear these files out of the `tmp/capybara` folder when run or does the command only affect certain folders in `tmp`?

I asked if capybara should take care of these files but was advised that it wouldn't (https://github.com/jnicklas/capybara/issues/1583) so thought I'd check whether it is something rake should (or could) be doing.

**Comment by hsbt** [comment]
It's not rake global task. `tmp:clear` task is rails specific task.

Please see https://github.com/rails/rails/blob/master/railties/lib/rails/tasks/tmp.rake#L3

**Comment by amnesia7** [comment]
Thanks @hsbt I've added an issue to the rails repo: https://github.com/rails/rails/issues/22050
