### ISSUE TITLE
rake-standalone: an initiative for a standard rake distribution

### ISSUE THREAD

**Issue by alanfranz** [ruby/rake#87]
Hello,
I do like rake quite a lot and I thank you for the effort spent on it. When trying to use it "professionally" (both at the companies where I've worked and in some open source projects) I've had to fight with "different behaviours" of rake caused by different versions installed around and/or different ruby versions.

Please note that my scope was far beyond Ruby projects: I want to use it in many situations, with other languages, as a substitute for crappy bash scripts or out-of-place GNU Makefiles.

So I've started this project to create a stable distribution for Rake with a stable API, which I dubbed Rake Standalone:

https://github.com/alanfranz/rake-standalone

I'd like to have some feedback from you: do you think it's interesting? Or do you feel it's not useful or straightly a bad idea?

**Comment by hsbt** [comment]
It's interesting. but I like idea with mruby and [mruby-cli](https://github.com/hone/mruby-cli) for rake standalone binary.
