### ISSUE TITLE
rake gem won't install

### ISSUE THREAD

**Issue by Shakyamuni177te** [ruby/rake#90]
When running ```gem install rake``` I get the following error: ```ERROR:  While executing gem ... (OpenSSL::X509::StoreError)```

Ruby seems to be able to install other gems just fine...

**Comment by Shakyamuni177te** [comment]
Found a workaround but rails shouldn't be getting SSH errors on a default gem...

**Comment by amosk** [comment]
I'm getting the same thing in Ubuntu 14.10

```
$ gem install rake
ERROR:  Could not find a valid gem 'rake' (>= 0) in any repository
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (http://rubygems.global.ssl.fastly.net/latest_specs.4.8.gz)
```

@Shakyamuni177te what was the work around?

**Comment by amosk** [comment]
@myself, this seemed to fix it...

```
$ sudo gem update
$ sudo gem install rake
```

**Comment by hsbt** [comment]
It's not rake issue. Please update rubygems or your ruby.
