### ISSUE TITLE
http://docs.rubyrake.org/ is down

### ISSUE THREAD

**Issue by llimllib** [ruby/rake#98]
Is this the appropriate place to report this? If not just redirect me and I'll be happy to post it elsewhere.

**Comment by hsbt** [comment]
Thanks reporting. It's only appear `doc/release_notes/rake-0.6.0.rdoc`

It's too old site. We uses http://docs.seattlerb.org/rake .

**Comment by llimllib** [comment]
There's no link to the correct documentation on http://rake.rubyforge.org/, which is the second google link for "ruby rake". Can I file a bug with somebody to fix it there? Because I was unable to find the correct link.

**Comment by hsbt** [comment]
rubyforge is already sunset. We only maintain http://docs.seattlerb.org/rake . Sorry, I don't know how to fix rubyforge and rubyrake links.
